language: r
sudo: false
cache: packages
warnings_are_errors: true
dist: xenial

r:
  - release

addons:
  apt:
    packages:
      - libcurl4-gnutls-dev
      - libgit2-dev
      - libssl-dev
      - libudunits2-dev
      - libprotobuf-dev
      - libv8-dev
      - libjq-dev
      - protobuf-compiler
      - libgdal-dev

#before_install:
#  - Rscript -e "install.packages(c('roxygen2', 'devtools', 'pkgdown', 'shinytest'))"

script:
  - _R_CHECK_TESTS_NLINES_=0
  - R CMD build .
  - R CMD check *tar.gz

after_success:
  - Rscript -e 'if (!require("covr")) install.packages("covr"); covr::codecov()'
  - Rscript -e 'if (!require("devtools")) install.packages("devtools"); devtools::document()'
  - Rscript -e 'if (!require("roxygen2")) install.packages("roxygen2"); roxygen2::roxygenise()'
  - Rscript -e 'if (!require("pkgdown")) install.packages("pkgdown"); pkgdown::build_site()'

deploy:
  provider: pages                         # Specify the gh-pages deployment method
  skip_cleanup: true                      # Don't remove files
  github_token: $GITHUB_TOKEN             # Set in travis-ci.org dashboard
  local_dir: docs                         # Deploy the docs folder
  on:
    branch: master

notifications:
  email: false
